[package]
name = "uninsyde"
version = "0.1.0"
authors = ["James Lee <jbit@jbit.net>"]
edition = "2018"
description = "Extract chunks from Insyde H2O Iflash files"
license = "MIT"
readme = "README.md"

[dependencies]
